In [1]:
import numpy as np

# 1. Create a 1D array with values 0 to 23
data = np.arange(24)

# 2. Reshape into (4, 3, 2): 4 batches of 3x2 matrices
reshaped_data = data.reshape(4, 3, 2)

# 3. Transpose to get shape (4, 2, 3)
final_data = reshaped_data.transpose(0, 2, 1)

# 4. Print results
print("Final shape:", final_data.shape)
print("\nFinal array:")
print(final_data)


Final shape: (4, 2, 3)

Final array:
[[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]

 [[12 14 16]
  [13 15 17]]

 [[18 20 22]
  [19 21 23]]]
